{
  "openapi": "3.0.3",
  "info": {
    "version": "1.0.1",
    "title": "GooseTrack",
    "description": "Personal to-do list website"
  },
  "consumes": ["application/json", "multipart/form-data"],
  "produces": ["application/json", "multipart/form-data"],
  "servers": [
    {
      "url": "https://goose-backend.onrender.com"
    }
  ],
  "tags": [
    {
      "name": "Auth",
      "description": "Authorization endpoints"
    },
    { "name": "Reviews", "description": "Reviews endpoints" },
    { "name": "Tasks", "description": "Tasks endpoints" }
  ],
  "paths": {
    "/users/register": {
      "post": {
        "tags": ["Auth"],
        "summary": "New user registration",
        "description": "This endpoint register new user in database",
        "parameters": [],
        "requestBody": {
          "description": "Registration object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "401": {
            "description": "Email or password is incorrect",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Login401error"
                }
              }
            }
          },
          "409": {
            "description": "This user is already exist",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Registration409error"
                }
              }
            }
          }
        }
      }
    },
    "/users/login": {
      "post": {
        "tags": ["Auth"],
        "summary": "User login",
        "description": "This endpoint login user",
        "parameters": [],
        "requestBody": {
          "description": "Login object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "401": {
            "description": "Email or password is incorrect",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Login401error"
                }
              }
            }
          }
        }
      }
    },
    "/users/logout": {
      "post": {
        "tags": ["Auth"],
        "summary": "User logout",
        "description": "This endpoint logout user",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LogoutResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized (invalid token or user not found)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Auth401error"
                }
              }
            }
          }
        }
      }
    },
    "/users/current": {
      "get": {
        "tags": ["Auth"],
        "summary": "Get current user",
        "description": "This endpoint gets information about current user",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized (invalid token or user not found)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Auth401error"
                }
              }
            }
          }
        }
      }
    },
    "/users/refresh": {
      "post": {
        "tags": ["Auth"],
        "summary": "Refresh tokens",
        "description": "This endpoint refreshes two security tokens",
        "parameters": [],
        "requestBody": {
          "description": "Tokens object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TokensRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TokensResponse"
                }
              }
            }
          },
          "403": {
            "description": "Invalid token error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Refresh403error"
                }
              }
            }
          }
        }
      }
    },
    "/users/user": {
      "patch": {
        "tags": ["Auth"],
        "summary": "User updating",
        "description": "This endpoint updates user's info in database",
        "security": [{ "Bearer": [] }],
        "parameters": [],
        "requestBody": {
          "description": "Updating object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateingRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdatingResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/Updating400error" }
              }
            }
          },
          "401": {
            "description": "Unauthorized: Authentication credentials are missing or invalid",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Auth401error"
                }
              }
            }
          }
        }
      }
    },
    "/users/avatars": {
      "patch": {
        "tags": ["Auth"],
        "summary": "Updating user's avatar",
        "description": "This endpoint updates user's auatarURL in database",
        "security": [{ "Bearer": [] }],
        "parameters": [],
        "requestBody": {
          "description": "Form-data",
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/UpdateingAvatarRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateingAvatarResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/Updating400error" }
              }
            }
          },
          "401": {
            "description": "Unauthorized: Authentication credentials are missing or invalid",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Auth401error"
                }
              }
            }
          }
        }
      }
    },
    "/reviews": {
      "get": {
        "tags": ["Reviews"],
        "summary": "Get all reviews of all",
        "description": "This endpoint retrieves all reviews of products or services.",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AllReviews"
                }
              }
            }
          },
          "404": {
            "description": "Reviews not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorReviews"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["Reviews"],
        "summary": "Add review",
        "description": "This endpoint allows user to add a  review for a product or service.",
        "security": [{ "Bearer": [] }],
        "parameters": [],
        "requestBody": {
          "description": "Review's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddReviewRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Review added successfully",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/AddReviewResponse" }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized: Authentication credentials are missing or invalid",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not Found: The specified resource was not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "409": {
            "description": "Conflict: The review could not be added due to a conflict with an existing resource",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/reviews/{id}": {
      "get": {
        "tags": ["Reviews"],
        "summary": "Get current user's review",
        "description": "Get the review of the current user for a product or service",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "type": "string",
            "description": "User's id"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserReview"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized: Authentication credentials are missing or invalid",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Reviews not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorReviews"
                }
              }
            }
          }
        }
      },
      "patch": {
        "tags": ["Reviews"],
        "summary": "Update review by user's id",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "user's id"
          }
        ],
        "requestBody": {
          "description": "Review's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PatchReviewRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PatchReviewResponses"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized: Authentication credentials are missing or invalid",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Reviews not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorReviews"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Reviews"],
        "summary": "Delete review",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "type": "string",
            "description": "User's id"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {}
          },
          "204": {
            "description": "Successful operation",
            "content": {}
          },
          "401": {
            "description": "Unauthorized (invalid access token)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Review not found / Invalid user / Invalid session",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "LoginRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "test2@i.ua"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "123456Qw"
          }
        }
      },
      "LoginResponse": {
        "type": "object",
        "properties": {
          "user": {
            "type": "object",
            "properties": {
              "_id": {
                "type": "string",
                "description": "User's id in database (type ObjectId)",
                "example": "64d5eb99a3ed01b542412a5f"
              },
              "name": {
                "type": "string",
                "description": "User's name",
                "example": "Joi"
              },
              "email": {
                "type": "string",
                "description": "User's email",
                "format": "email"
              },
              "avatarURL": {
                "type": "string",
                "description": "User's avatar URL",
                "example": "https://vrt.com/upload/avatar.jpg"
              },
              "refresh_token": {
                "type": "string",
                "description": "Refresh token",
                "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZDVlYjk5YTNlZDAxYjU0MjQxMmE1ZiIsImlhdCI6MTY5MjAxMDg4NywiZXhwIjoxNjk0NjAyODg3fQ.6y6K88bc38--1DYZN79FgvUyw4kMnFEhczicJymkguc"
              }
            }
          },
          "token": {
            "type": "string",
            "description": "Access token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZDVlYjk5YTNlZDAxYjU0MjQxMmE1ZiIsImlhdCI6MTY5MjAxMDg4NywiZXhwIjoxNjk0NjAyODg3fQ.6y6K88bc38--1DYZN79FgvUyw4kMnFEhczicJymkguc"
          }
        }
      },
      "RegistrationRequest": {
        "type": "object",
        "required": ["name", "email", "password"],
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Joi"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "test2@i.ua"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "123456Qw"
          }
        }
      },
      "TokensRequest": {
        "type": "object",
        "required": ["refresh_token"],
        "properties": {
          "refresh_token": {
            "type": "string",
            "description": "Access token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZDVlYjk5YTNlZDAxYjU0MjQxMmE1ZiIsImlhdCI6MTY5MjAxMDg4NywiZXhwIjoxNjk0NjAyODg3fQ.6y6K88bc38--1DYZN79FgvUyw4kMnFEhczicJymkguc"
          }
        }
      },
      "TokensResponse": {
        "type": "object",
        "properties": {
          "token": {
            "type": "string",
            "description": "Access token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZDVlYjk5YTNlZDAxYjU0MjQxMmE1ZiIsImlhdCI6MTY5MjAxMDg4NywiZXhwIjoxNjk0NjAyODg3fQ.6y6K88bc38--1DYZN79FgvUyw4kMnFEhczicJymkguc"
          },
          "refresh_token": {
            "type": "string",
            "description": "Refresh token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZDVlYjk5YTNlZDAxYjU0MjQxMmE1ZiIsImlhdCI6MTY5MjAxMDg4NywiZXhwIjoxNjk0NjAyODg3fQ.6y6K88bc38--1DYZN79FgvUyw4kMnFEhczicJymkguc"
          }
        }
      },
      "LogoutResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "example": "Logout successful"
          }
        }
      },
      "UpdateingRequest": {
        "type": "object",
        "required": ["name", "email", "password"],
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Joi"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "test2@i.ua"
          },
          "phone": {
            "type": "string",
            "description": "User's phone number",
            "example": "38 (000) 123 45 67"
          },
          "skype": {
            "type": "string",
            "description": "User's skype number",
            "example": "38 (000) 123 45 67"
          },
          "birthday": {
            "type": "string",
            "description": "User's date of birth",
            "example": "2000-02-20"
          }
        }
      },
      "UpdatingResponse": {
        "type": "object",
        "properties": {
          "user": {
            "type": "object",
            "properties": {
              "_id": {
                "type": "string",
                "description": "User's id in database (type ObjectId)",
                "example": "64d5eb99a3ed01b542412a5f"
              },
              "name": {
                "type": "string",
                "description": "User's name",
                "example": "Joi"
              },
              "email": {
                "type": "string",
                "description": "User's email",
                "format": "email",
                "example": "test2@i.ua"
              },
              "phone": {
                "type": "string",
                "description": "User's phone number",
                "example": "38 (000) 123 45 67"
              },
              "skype": {
                "type": "string",
                "description": "User's skype number",
                "example": "38 (000) 123 45 67"
              },
              "birthday": {
                "type": "string",
                "description": "User's date of birth",
                "example": "2000-02-20"
              },
              "avatarURL": {
                "type": "string",
                "description": "User's avatar URL",
                "example": "https://vrt.com/upload/avatar.jpg"
              },
              "refresh_token": {
                "type": "string",
                "description": "Refresh token",
                "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZDVlYjk5YTNlZDAxYjU0MjQxMmE1ZiIsImlhdCI6MTY5MjAxMDg4NywiZXhwIjoxNjk0NjAyODg3fQ.6y6K88bc38--1DYZN79FgvUyw4kMnFEhczicJymkguc"
              }
            }
          },
          "token": {
            "type": "string",
            "description": "Access token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZDVlYjk5YTNlZDAxYjU0MjQxMmE1ZiIsImlhdCI6MTY5MjAxMDg4NywiZXhwIjoxNjk0NjAyODg3fQ.6y6K88bc38--1DYZN79FgvUyw4kMnFEhczicJymkguc"
          }
        }
      },
      "UpdateingAvatarRequest": {
        "type": "object",
        "required": ["name", "email", "password"],
        "properties": {
          "avatar": {
            "type": "string",
            "format": "binary",
            "description": "User's avatar",
            "example": "beautiful_picture.png"
          }
        }
      },
      "UpdateingAvatarResponse": {
        "type": "object",
        "required": ["name", "email", "password"],
        "properties": {
          "avatarURL": {
            "type": "string",
            "description": "User's avatar file name",
            "example": "avatars\\64d8d42de77a75cf6008418a_beautiful_picture.png"
          }
        }
      },
      "Login401error": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "example": "Email or password is incorrect"
          },
          "status": {
            "type": "integer",
            "example": 401
          }
        }
      },
      "Registration409error": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "example": "This user is already exist"
          },
          "status": {
            "type": "integer",
            "example": 409
          }
        }
      },
      "Refresh403error": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "example": "Invalid token"
          },
          "status": {
            "type": "integer",
            "example": 403
          }
        }
      },
      "Auth401error": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "example": "Unauthorized"
          },
          "status": {
            "type": "integer",
            "example": 401
          }
        }
      },
      "Updating400error": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "example": "Bad request"
          },
          "status": {
            "type": "integer",
            "example": 400
          }
        }
      },
      "AllReviews": {
        "type": "array",
        "description": "An array containing all user reviews",
        "required": ["comment", "rating"],
        "properties": {
          "comment": {
            "type": "string",
            "description": "User's comment about the product or service",
            "maxLength": 300
          },
          "rating": {
            "type": "integer",
            "description": "User's rating of the product or service",
            "minimum": 1,
            "maximum": 5
          },
          "owner": {
            "type": "object",
            "description": "Information about the user who left the review",
            "properties": {
              "name": {
                "type": "string",
                "description": "User's name"
              },
              "avatarURL": {
                "type": "string",
                "description": "URL to the user's avatar image"
              }
            }
          }
        },
        "example": [
          {
            "rating": 5,
            "comment": "Really helps to plan the day and visualize tasks. Exactly what I was looking for. Huge thanks to the developers!",
            "owner": {
              "name": "Kateryna Hilcher",
              "avatarURL": "https://example.com/avatar.jpg"
            }
          },
          {
            "rating": 4,
            "comment": "A good, visual time planning program.",
            "owner": {
              "name": "Volodymyr Shvets",
              "avatarURL": "https://example.com/avatar.jpg"
            }
          }
        ]
      },
      "ErrorResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "description": "Error description"
          },
          "example": {
            "type": "string",
            "description": "Example error description",
            "value": "Here is an error description"
          }
        }
      },
      "AddReviewRequest": {
        "type": "object",
        "required": ["rating", "comment"],
        "properties": {
          "rating": {
            "type": "integer",
            "description": "Review rating",
            "minimum": 1,
            "maximum": 5
          },
          "comment": {
            "type": "string",
            "description": "Review comment"
          }
        }
      },
      "AddReviewResponse": {
        "type": "object",
        "description": "Data structure for adding a new user review",
        "required": ["comment", "rating"],
        "properties": {
          "comment": {
            "type": "string",
            "description": "User's comment about the product or service",
            "maxLength": 300
          },
          "rating": {
            "type": "integer",
            "description": "User's rating of the product or service",
            "minimum": 1,
            "maximum": 5
          },
          "owner": {
            "type": "object",
            "description": "Information about the user leaving the review",
            "properties": {
              "name": {
                "type": "string",
                "description": "User's name"
              },
              "avatarURL": {
                "type": "string",
                "description": "URL to the user's avatar image"
              }
            }
          }
        },
        "example": {
          "rating": 5,
          "comment": "Really helps to plan the day and visualize tasks. Exactly what I was looking for. Huge thanks to the developers!",
          "owner": {
            "name": "Kateryna Hilcher",
            "avatarURL": "https://example.com/avatar.jpg"
          }
        }
      },
      "UserReview": {
        "type": "object",
        "description": "Get the review of the current user for a product or service",
        "required": ["comment", "rating"],
        "properties": {
          "comment": {
            "type": "string",
            "description": "User's comment about the product or service",
            "maxLength": 300
          },
          "rating": {
            "type": "integer",
            "description": "User's rating of the product or service",
            "minimum": 1,
            "maximum": 5
          },
          "owner": {
            "type": "object",
            "description": "Information about the user leaving the review",
            "properties": {
              "name": {
                "type": "string",
                "description": "User's name"
              },
              "avatarURL": {
                "type": "string",
                "description": "URL to the user's avatar image"
              }
            }
          }
        },
        "example": {
          "rating": 5,
          "comment": "Really helps to plan the day and visualize tasks. Exactly what I was looking for. Huge thanks to the developers!",
          "owner": {
            "name": "Kateryna Hilcher",
            "avatarURL": "https://example.com/avatar.jpg"
          }
        }
      },
      "PatchReviewRequest": {
        "type": "object",
        "required": ["rating", "comment"],
        "properties": {
          "rating": {
            "type": "integer",
            "description": "Review rating",
            "minimum": 1,
            "maximum": 5
          },
          "comment": {
            "type": "string",
            "description": "Review comment"
          }
        }
      },
      "PatchReviewResponses": {
        "type": "object",
        "description": "Data structure for changing user review",
        "required": ["comment", "rating"],
        "properties": {
          "comment": {
            "type": "string",
            "description": "User's comment about the product or service",
            "maxLength": 300
          },
          "rating": {
            "type": "integer",
            "description": "User's rating of the product or service",
            "minimum": 1,
            "maximum": 5
          },
          "owner": {
            "type": "object",
            "description": "Information about the user leaving the review",
            "properties": {
              "name": {
                "type": "string",
                "description": "User's name"
              },
              "avatarURL": {
                "type": "string",
                "description": "URL to the user's avatar image"
              }
            }
          }
        },
        "example": {
          "rating": 5,
          "comment": "Really helps to plan the day and visualize tasks. Exactly what I was looking for. Huge thanks to the developers!",
          "owner": {
            "name": "Kateryna Hilcher",
            "avatarURL": "https://example.com/avatar.jpg"
          }
        }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "BearerFormat": "JWT",
        "in": "header",
        "name": "Authorization",
        "description": "Bearer token to access these API endpoints"
      }
    }
  }
}
